language: ruby
rvm:
- 2.5.1
services:
- postgresql
before_script:
- psql -c 'create database makers_bnb_test;' -U postgres
script:
- bundle exec rake db:test:prepare
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key: 15db3623-e3a9-4798-b701-31f8c3af2aae
  app: makers-bnb-oct
  on:
    repo: toddpla/makersbnb
    branch: master
