language: ruby
rvm:
  - 2.5.1

services:
  - postgresql

before_script:
  - psql -c 'create database makers_bnb_test;' -U postgres
  - rake db:migrate
  - rake db:test:prepare

script:
  - bundle exec rspec spec
