development:
  adapter: postgresql
  encoding: unicode
  database: makers_bnb
  pool: 2
  # username: your_username
  # password: your_password

production:
  adapter: postgresql
  encoding: unicode
  database: makers_bnb
  pool: 2
  # username: your_username
  # password: your_password
