development:
  adapter: postgresql
  encoding: unicode
  database: makers_bnb
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: makers_bnb
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: makers_bnb_test
  pool: 5
