development:
  adapter: postgresql
  encoding: unicode
  database: makers_bnb
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: makers_bnb
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: makers_bnb_test
  pool: 2
